language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab8_9-stack_queue_on_list
  - make -j
  - cd ./bin/
  - ./test/SQOL_test
notifications:
  email: false
